### ISSUE TITLE
Fails to retrieve Google Keep Sync Token

### ISSUE THREAD

**Issue by emperorcollins** [lc0rp/KeepSidian#3]
everytime, curious if this is a known issue and is there another way to find it?

**Comment by lc0rp** [comment]
@emperorcollins please share the following details;
- Description of what the bug is
- Steps to reproduce
- Screenshots, if possible
- Operating system
- Browser & version

**Comment by Juan-Rauld** [comment]
Description of what the bug is: it freezes after you hit approve terms in final google auth step.
Steps to reproduce: fresh install of the plugin (as i'm now) and just try to retreive.
Screenshots, if possible
Here a Loom with the issue:
https://www.loom.com/share/3cca9e961b7947a993c122326a88025c

Operating system: macOS 15.1.1 (24B91)
Browser & version: native obsidian macOS app v 1.7.7

**Comment by lc0rp** [comment]
Thank you for sharing the Loom video. It seems that the token registration process is not recognizing that you have accepted the terms, which is preventing you from moving on to step 3.

I believe I have identified the issue: it appears to be related to the interface language. I am using the button text to determine whether the terms have been accepted. This bug will be fixed in the next release, which is scheduled for later this week.

In the meantime, could you please switch your interface language to English temporarily and see if that allows you to proceed beyond this point? 

Thank you!

**Comment by michaje** [comment]
Same problem still exists using Windows/German. I'm not sure what language setting it is related to either, I now changed language to English in google, windows and obsidian but for some reason the login window is still in English and the problem persists.

**Comment by michaje** [comment]
I can confirm that the same problem still exists for me. The problem persists after changing display language to English as well.

**Comment by ms3056** [comment]
Yep - everything has been working well and now this looks like a regression.

**Comment by hinchcliffe** [comment]
This issue is still occurring 

<img width="760" alt="Image" src="https://github.com/user-attachments/assets/4fbadf68-1849-44f0-8926-4ca5516715be" />

**Comment by lc0rp** [comment]
Sorry to hear that. I'm working on adding manual token input.

**Comment by robin-collins** [comment]
Same issue for me also

**Comment by dudinhabranco** [comment]
I install the plugin, go to settings an use ctrl+shift+i to debug and error show at start:

Failed to load resource: the server responded with a status of 500 () 
https://keepsidianserver-i55qr5tvea-uc.a.run.app/subscriber/info

Failed to check subscription: Error: Internal server error: find_stripe_customer Stripe service error: Invalid API Key provided: Test
    at SubscriptionService.fetchSubscriptionInfo (plugin:keepsidian:827:13)
    at async SubscriptionService.checkSubscription (plugin:keepsidian:805:20)
    at async SubscriptionService.isSubscriptionActive (plugin:keepsidian:832:18)
    at async SubscriptionSettingsTab.display (plugin:keepsidian:374:10)

Im starting with plugins develop and debuging and dont know ts só i can't help more.

**Comment by lc0rp** [comment]
> I install the plugin, go to settings an use ctrl+shift+i to debug and error show at start:
> 
> Failed to load resource: the server responded with a status of 500 () [keepsidianserver-i55qr5tvea-uc.a.run.app/subscriber/info](https://keepsidianserver-i55qr5tvea-uc.a.run.app/subscriber/info)
> 
> Failed to check subscription: Error: Internal server error: find_stripe_customer Stripe service error: Invalid API Key provided: Test at SubscriptionService.fetchSubscriptionInfo (plugin:keepsidian:827:13) at async SubscriptionService.checkSubscription (plugin:keepsidian:805:20) at async SubscriptionService.isSubscriptionActive (plugin:keepsidian:832:18) at async SubscriptionSettingsTab.display (plugin:keepsidian:374:10)
> 
> Im starting with plugins develop, debuging and dont know ts, so i can't help more.

Hey @dudinhabranco - I pushed a fix for this. Let me know if you're still having an issue.

**Comment by lc0rp** [comment]
> I can confirm that the same problem still exists for me. The problem persists after changing display language to English as well.
> 
> Suggested fix - maybe allow manual oauth token login like when logging into KIM manually?

@michaje - I just released 1.0.15, which enables the manual setting of the Google Keep sync token. Check it out and let me know. Thanks.

**Comment by Kaos-07** [comment]
Hello, I still have the same issue the Loom video

windows 10
obsidia v1.8.10
keepsidian v1.0.15



<img width="437" height="478" alt="Image" src="https://github.com/user-attachments/assets/081fe8e0-da68-4749-a5b3-67be3f97d64b" />

**Comment by nachbelichtet** [comment]
If you're using Docker, you can use this container, which actually belongs to Home Assistant:

https://github.com/Brephlas/dockerfile_breph-ha-google-home_get-token

Just build the container

`docker run -it --rm breph/ha-google-home_get-token:latest python3 get_tokens.py`

enter your Gmail-address and enter your application (!) password. It doesn't work with your normal Gmail password. 
https://myaccount.google.com/apppasswords

Copy the Master-Token (the first one) and paste it in the Sync Token field of the plugin.
Worked for me.

**Comment by marcelespunkt** [comment]
I also have the exact same issue people above are describing.
